class Food {
  String name;
  String description;
  String imgUrl;
  String serveTime;
  int price;
  int calories;
  String weight;
  bool isFav;
  Food({
    this.name,
    this.description,
    this.imgUrl,
    this.price,
    this.serveTime,
    this.calories,
    this.weight,
    this.isFav,
  });
}

String _soupDescription =
    'Some soups are served with large chunks of meat or vegetables left in the liquid, while others are served as a broth. A broth is a flavored liquid usually derived from boiling a type of meat with bone, a spice mix, or a vegetable mix for a period of time in a stock. A potage is a category of thick soups, stews, or porridges, in some of which meat and vegetables are boiled together with water until they form a thick mush. Bisques are heavy cream soups traditionally prepared with shellfish, but can be made with any type of seafood or other base ingredients. Cream soups are dairy based soups. Although they may be consumed on their own, or with a meal, the canned, condensed form of cream soup is sometimes used as a quick sauce in a variety of meat and pasta convenience food dishes, such as casseroles. Similar to bisques, chowders are thick soups usually containing some type of starch.';
String _steakDescription =
    'Beefsteak is a flat cut of beef, usually cut perpendicular to the muscle fibers. Beefsteaks are usually grilled, pan-fried, or broiled. The more tender cuts from the loin and rib are cooked quickly, using dry heat, and served whole. Less tender cuts from the chuck or round are cooked with moist heat or are mechanically tenderized.';
String _pizzaDescription =
    'in Italy, pizza has gone through numerous transformations to become the dish that so many people know and love today. But if you’re just opening your first pizza place or want to add a pizza oven in your restaurant, it can be difficult to decide what style of pizza your restaurant will make. We discuss the different types of pizza, their history, and what you’ll need to make them, so you can start serving up delicious slices to your guests.';
String _pastaDescription =
    'There are many different varieties of pasta.[1] They are usually sorted by size, being long (pasta lunga), short (pasta corta), stuffed (ripiena), cooked in broth (pastina), stretched (strascinati) or in dumpling-like form (gnocchi/gnocchetti). Yet, due to the variety of shapes and regional variants, "one man\'s gnocchetto can be another\'s strascinato". Some pasta varieties are uniquely regional and not widely known; many types have different names based on region or language. For example, the cut rotelle is also called ruote in Italy and wagon wheels in the United States. Manufacturers and cooks often invent new shapes of pasta, or may rename pre-existing shapes for marketing reasons. Italian pasta names often end with the masculine plural diminutive suffixes -ini, -elli, -illi, -etti or the feminine plurals -ine, -elle etc., all conveying the sense of "little"; or with the augmentative suffixes -oni, -one, meaning "large". Other suffixes like -otti ("largish") and -acci ("rough", "badly made") may also occur. In Italian, all pasta type names are plural.';
String _hamburgerList =
    'A hamburger made using beef from Angus cattle. The name "Angus burger" is used by several fast-food hamburger chains for one or more "premium" burgers; however, it does not belong to any single company. Pre-made frozen Angus burgers are increasingly available from retailers.';

List soupList = [
  Food(
      name: 'Chicken Noodle Soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG95.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Lentil soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG12.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Bacon soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG22.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Beef Noodle soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG35.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Cheese soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG14.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Cream of tomato',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG52.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Gumbo',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG80.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Curry Mee',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG86.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Gazpacho',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG98.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Minestrone',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG99.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Vegetable soup',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG100.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Solyanka',
      description: _soupDescription,
      imgUrl: 'assets/images/food/soup_PNG100.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
];

List steakList = [
  Food(
      name: 'Beef Manhattan',
      description: _steakDescription,
      imgUrl: 'assets/images/food/steak_PNG24.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Fajita',
      description: _steakDescription,
      imgUrl: 'assets/images/food/steak_PNG44.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Pittsburgh rare',
      description: _steakDescription,
      imgUrl: 'assets/images/food/steak_PNG47.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Delmonico steak',
      description: _steakDescription,
      imgUrl: 'assets/images/food/steak_PNG48.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Steak au poivre',
      description: _steakDescription,
      imgUrl: 'assets/images/food/steak_PNG52.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
];

List pizzaList = [
  Food(
      name: 'Detroit Pizza',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/9-pizza-png-image.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Greek Pizza',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/7-pizza-png-image.png',
      price: 30,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'St. Louis Pizza',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/4-pizza-png-image.png',
      price: 25,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Quattro Stagioni',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44037.png',
      price: 10,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Calzone',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44046.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Quattro Stagioni',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44051.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Marinara',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44053.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Frutti di mare',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44053.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Vegetariana',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44092.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Hawaii',
      description: _pizzaDescription,
      imgUrl: 'assets/images/food/pizza_PNG44092.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
];

List pastaList = [
  Food(
      name: 'Casunziei ampezzani',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG18.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Spaghetti allo scoglio',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG34.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Penne all’arrabbiata',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG63.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Spaghetti alla carrettiera',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG67.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Ziti al forno',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG93.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Fettuccine',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG95.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Insalata di pasta',
      description: _pastaDescription,
      imgUrl: 'assets/images/food/pasta_PNG96.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
];

List burgerList = [
  Food(
      name: 'Slugburger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96745.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Barbecue burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96755.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Chili burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96761.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Chicken burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/9-2-burger-png-hd.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Buffalo burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96773.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
  Food(
      name: 'Salmon burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96781.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: true),
  Food(
      name: 'Steak burger',
      description: _hamburgerList,
      imgUrl: 'assets/images/food/burger_sandwich_PNG96783.png',
      price: 20,
      serveTime: '10 min',
      calories: 80,
      weight: '400 gr',
      isFav: false),
];
